CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python -m torch.distributed.launch --nproc_per_node 8 train_ddp.py \
  --model dsp \
  --loss dsp \
  --features_dir data_argo/features/ \
  --obs_len 20 \
  --pred_len 30 \
  --train_batch_size 16 \
  --val_batch_size 16 \
  --val_interval 2 \
  --train_epoches 45 \
  --data_aug \
  --use_cuda True \
  --logger_writer True \
  --logger_mailbot False \
  --adv_cfg_path config.dsp_cfg